apiVersion: v1
version: 6.11.3
appVersion: 6.11.3
name: pod2info
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/MichaelMorrisEst/podinfo
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
sources:
- https://github.com/MichaelMorrisEst/podinfo
kubeVersion: ">=1.23.0-0"
